name: Fetch upstream

on: 
  push:
  schedule:
    - cron: "0 16 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: GitHub Sync to Upstream Repository
      uses: tjusl/sync-upstream-repo@master
      with:
        upstream_repo: https://github.com/gitpod-io/openvscode-releases.git
        upstream_branch: main
        local_branch: main
        github_token: ${{ secrets.FETCH_UPSTREAM }}
